### ISSUE TITLE
require('events') doesn't work on Node 12

### ISSUE THREAD

**Issue by tabone** [patriksimek/vm2#216]
While I was working on https://github.com/patriksimek/vm2/pull/215, I executed the unit tests to make sure that everything works fine. However, they failed.

The problem was with `NodeVM > modules > native event emitter` test:

```
  70 passing (483ms)
  2 pending
  1 failing

  1) modules
       native event emitter:
     Cannot find module 'internal/util/inspect'
Require stack:
- /Users/tabone/Documents/Development/vm2/lib/main.js
- /Users/tabone/Documents/Development/vm2/index.js
- /Users/tabone/Documents/Development/vm2/test/nodevm.js
- /Users/tabone/Documents/Development/vm2/node_modules/mocha/lib/mocha.js
- /Users/tabone/Documents/Development/vm2/node_modules/mocha/index.js
- /Users/tabone/Documents/Development/vm2/node_modules/mocha/bin/_mocha
  Error: Cannot find module 'internal/util/inspect'
  Require stack:
  - /Users/tabone/Documents/Development/vm2/lib/main.js
  - /Users/tabone/Documents/Development/vm2/index.js
  - /Users/tabone/Documents/Development/vm2/test/nodevm.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
      at Function.Module._load (internal/modules/cjs/loader.js:527:27)
      at Module.require (internal/modules/cjs/loader.js:681:19)
      at Object.require (internal/modules/cjs/helpers.js:16:16)
      at _requireBuiltin (lib/sandbox.js:203:35)
      at events.vm.js:39:5
      at _requireBuiltin (lib/sandbox.js:195:32)
      at _require (lib/sandbox.js:245:12)
      at Object.<anonymous> (vm.js:1:84)
      at NodeVM.run (lib/main.js:447:23)
      at Context.<anonymous> (test/nodevm.js:367:6)
      at processImmediate (internal/timers.js:439:21)
```

After some investigation, I learnt that the problem was caused by the inclusion of the following dependency on NodeJS's `events` built-in module. (https://github.com/nodejs/node/commit/9375088bd3df5a1bd2c4dfc5be1b1d37a7fe2dda#diff-71dcd327d0ca067b490b22d677f81966R34).

I'm new to `vm2`, and I'm looking for what options I can use to create a new PR to fix this test.

**Comment by tabone** [comment]
FYI I'm working with `NodeV12.3.1`.

**Comment by tabone** [comment]
So I have investigated further and noticed `vm2` already has some conditions to handle the `events` & `internal` dependencies, as one can see here: https://github.com/patriksimek/vm2/blob/4e24a163fae5785913446701c7f89645020aac01/lib/sandbox.js#L177

So included an additional condition for `internal/util/inspect`:

```javascript
if (moduleName === 'events'
  || moduleName === 'internal/errors'
  || moduleName === 'internal/util/inspect' ) {
```

However, the `internal/util/inspect`module is expecting the `primordials` (which in our case is `global`) to have `ObjectPrototype` as one can see here:

https://github.com/nodejs/node/blob/master/lib/internal/util/inspect.js#L13

Will keep you updated!

**Comment by asprouse** [comment]
@tabone Any update on this?

**Comment by patriksimek** [comment]
I did some research on that and it's obvious we can no longer compile native modules inside the sandbox. There was a change in how Node load internals and since the new `internalBinding` method is not accessible from userland, we can't load libraries required by internal `events` module.

More info here: https://medium.com/front-end-weekly/internals-of-node-advance-node-%EF%B8%8F-8612f6a957d7

I can only see two ways out of this situation:
1) Drop support for EventEmitter inside the sandbox
2) Add custom implementation of EventEmitter

Any help is very welcome.

**Comment by cyberwombat** [comment]
@patriksimek any suggestions for a workaround? pretty showstopper issue for me. I load webpacked code in VM (well was hoping) but most of it at some point loads 1events`. I tried adding it to the import config but that doesn't seem to help.

**Comment by stwiname** [comment]
Why was this closed? Its still an issue (including with node 16)

**Comment by XmiliaH** [comment]
We now include a copy of the event module which does not depend on node internal modules. Therefore, this should be fixed. If there are still issues please open a new issue with the details.
